LapShop/LapShop/Areas/admin/Controllers/ItemController.cs
using Bl;
using Domains;
using LapShop.Models;
using LapShop.Utlities;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.admin.Controllers
{
    [Area("admin")]
    public class ItemController : Controller
    {
        Iitems Oclsitems;
        Icategories Oclscategories;
        public ItemController(Iitems clsitems,Icategories clscategories)
        {
            Oclsitems = clsitems;
            Oclscategories = clscategories;
        }
        public IActionResult List()
        {
            var item=Oclsitems.GetALLitemcategory();
            return View(item);
        }
       
        public List<VwItemHomePage> ajaxdata()
        {
            var item = Oclsitems.GetALLitemcategory();
            return item;
        }
        public IActionResult ajaxlist()
        {

            return View();
        }
        public IActionResult Edite(int? id)
        {
            var item = new ItemModel();
            ViewBag.LstCategoryid = Oclscategories.GetCategoryId();

            if (id != null) 
            {
              var itemid = Oclsitems.GetById(Convert.ToInt32(id));
                item.ItemId=itemid.ItemId;
                item.ItemName=itemid.ItemName;
                item.SalesPrice=itemid.SalesPrice;
                item.PurchasePrice=itemid.PurchacePrice;
                item.ImageName=itemid.imagename;
            }

            return View(item);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task< IActionResult>  Save(ItemModel item,List<IFormFile> Files)
        {
            if (!ModelState.IsValid)
                return View("Edite", item);
            else
            {
              
                Tbitem otbitem = new Tbitem()
                {

                    ItemId = item.ItemId,
                    ItemName = item.ItemName,
                    SalesPrice = item.SalesPrice,
                    PurchacePrice = item.PurchasePrice,
                    imagename= await Helper.UploadImage(Files, "Items"),
                    Categoryid=item.CategoryId,
                    
                };
            Oclsitems.Save(otbitem);

            }

            return RedirectToAction("List");
        }
        public IActionResult Delete(int id)
        {
            Oclsitems.Delete(id);
            return RedirectToAction("List");
        }
    }
}

LapShop/LapShop/Areas/admin/Views/Item/Edite.cshtml
@model ItemModel

<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title"> Form elements </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Forms</a></li>
                <li class="breadcrumb-item active" aria-current="page">Form elements</li>
            </ol>
        </nav>
    </div>
    <form class="forms-sample" method="post" enctype="multipart/form-data"
          asp-controller="Item" asp-action="Save" role="form">
        <div class="row">

            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Default form</h4>
                        <p class="card-description"> Basic form layout </p>

                        <input type="hidden" asp-for="ItemId" />
                        <div class="form-group">
                            <label for="exampleInputUsername1">ItemName</label>
                            <input asp-for="ItemName" type="text" class="form-control" placeholder="ItemName">
                            <span asp-validation-for="ItemName"></span>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputUsername1">CategoryName</label>
                            <select class="form-control" asp-for="CategoryId" asp-items="@(new SelectList(ViewBag.LstCategoryid, "Categoryid", "CategoryName"))"></select>
                            <span asp-validation-for="CategoryId"></span>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputUsername1">SalesPrice</label>
                            <input asp-for="SalesPrice" type="text" class="form-control" placeholder="SalesPrice">
                            <span asp-validation-for="SalesPrice"></span>
                        </div>

                        <div class="form-group">
                            <label for="exampleInputUsername1">PurchasePrice</label>
                            <input asp-for="PurchasePrice" type="text" class="form-control" placeholder="PurchasePrice">
                            <span asp-validation-for="PurchasePrice"></span>
                        </div>

                     

                        <div class="form-group">
                            <label for="exampleInputUsername1">
                                Image
                            </label>
                            <input asp-for="ImageName" type="file" name="Files" multiple
                                   class="form-control" placeholder="Image"
                                   onchange="Upload.UploadDefaultImg(event)" accept=".jpg, .jpeg, .png, ,.gif">

                        </div>
                        <span id="tbImgName"></span>
                        <div id="tbImgSrc">
                            <img src="/Uploads/Items/@Model.ImageName" style="width:95%; height300px;" />
                        </div>

                        <button type="submit" formmethod="post" class="btn btn-gradient-primary me-2">Save</button>
                        <button class="btn btn-light">New</button>

                    </div>
                </div>
            </div>

          


        </div>
    </form>
</div>

@section Scripts
{
    <script>
        var Upload = {
            UploadDefaultImg: function(e) {
                const file = e.target.files[0];
                const reader = new FileReader();
                reader.onloadend = () => {
                    CourseMediaImgName = file.name;
                    CourseMediaImgBase64 = reader.result.slice(reader.result.indexOf('base64,') + 7);
                    $("#tbImgName").html(file.name)
                    $("#tbImgSrc").html(`<img class="thumbnail" src = "${reader.result}"  style = "width: 200px;height: 300px;border-radius: 5px;border: 1px solid #d9d9d9;padding: 1px;" />`)
                };
                reader.readAsDataURL(file);
            }
        }
    </script>
}

LapShop/LapShop/Areas/admin/Views/Item/List.cshtml
@model List<VwItemCategory>
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic Table</h4>
            <p class="card-description">
                Add class <code>.table</code>
            </p>
            <a href="/admin/Item/Edite">New</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>itemname</th>
                        <th>categoryname</th>
                        <th>SalesPrice</th>
                        <th>PurchacePrice</th>
                        <th>Edite</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.itemname</td>
                            <td>@item.categoryname</td>
                            <td>@item.SalesPrice</td>
                            <td>@item.PurchacePrice</td>
                            <td>
                                <a asp-controller="Item" asp-action="Edite" asp-route-id="@item.itemid">Edite</a>
                            </td>
                            <td>
                                <a asp-controller="Item" asp-action="Delete" asp-route-id="@item.itemid">Delete</a>
                            </td>
                        </tr>
                    }
                  
                 
                </tbody>
            </table>
        </div>
    </div>
</div>

LapShop/LapShop/Areas/admin/Views/Item/ajaxlist.cshtml
<div class="col-lg-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Basic Table</h4>
            <p class="card-description">
                Add class <code>.table</code>
            </p>
            <a href="/admin/Item/Edite">New</a>
            <table class="table">
                <thead>
                    <tr>
                        <th>itemname</th>
                        <th>categoryname</th>
                        <th>SalesPrice</th>
                        <th>PurchacePrice</th>
                      
                    </tr>
                </thead>
                <tbody id="ItemArea">
                    
                      
                    


                </tbody>
            </table>
        </div>
    </div>
</div>
@section Scripts {

    <script src="~/modules/helper.js"></script>
    <script src="~/modules/item.js"></script>
    <script>
        ClsItems.GetAll();

    </script>
}