LapShop/LapShop/Areas/admin/Controllers/RolesController.cs
using Bl;
using Domains;
using LapShop.Models;
using LapShop.Utlities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LapShop.Areas.admin.Controllers
{
    [Area("admin")]
    public class RolesController : Controller
    {
        RoleManager<IdentityRole> _rolemanager;
        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            _rolemanager = roleManager;
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRole(RoleModel model)
        {
            if (!ModelState.IsValid)
                return View("CreateRole", model);
            if (model.id == null)
            {
                IdentityRole user = new IdentityRole()
                {
                    
                    Name = model.name.ToUpper()
                };
                IdentityResult result = await _rolemanager.CreateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Rolelist");
                }
                else
                {
                    return View("CreateRole", model);
                }
            }
            else
            {

                var Role = await _rolemanager.FindByIdAsync(model.id);
                Role.Name = model.name;
                var result = await _rolemanager.UpdateAsync(Role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Rolelist");

                }
                else
                {
                    return View("CreateRole", model);

                }
            }




        }
        public async Task<IActionResult> CreateRole(string? id)
        {
            var role = new RoleModel();
            if (id != null)
            {
                var roleid = await _rolemanager.FindByIdAsync(id);
                role.id = roleid.Id;
                role.name = roleid.Name;

            }
            return View(role);

        }
        public IActionResult Rolelist()
        {
            var roles = _rolemanager.Roles.ToList();
            return View(roles);
        }
        public async Task<IActionResult> DeleteRole(string id)
        {

            var roles = await _rolemanager.FindByIdAsync(id);
            if (roles != null)
            {
                await _rolemanager.DeleteAsync(roles);
            }
            else
            {
                return RedirectToAction("Rolelist");

            }

            return RedirectToAction("Rolelist");


        }
    }
}

LapShop/LapShop/Areas/admin/Views/Roles/CreateRole.cshtml
@model RoleModel


<!--section start-->
<section class="register-page section-b-space">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>create account</h3>
                <div class="theme-card">
                    <form class="theme-form" method="post"
                          asp-controller="Roles" asp-action="CreateRole">
                        <div class="form-row">

                            <input type="hidden" asp-for="id" />
                            <div class="col-md-6">
                                <label for="email">First Name</label>
                                <input asp-for="name"
                                       type="text" class="form-control" id="fname" placeholder="First Name"
                                       required="">
                                <span asp-validation-for="name"></span>
                            </div>
                          
                        </div>
                        <div class="form-row">
                          
                            <button type="submit" class="btn btn-solid">create a role</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--Section ends-->
@section Scripts{

}

LapShop/LapShop/Areas/admin/Views/Roles/Rolelist.cshtml
@model List<IdentityRole>


@section Styles
{
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/assets/Backend/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <!-- End plugin css for this page -->
}


<div class="container-fluid page-body-wrapper">
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="page-header">
                <h3 class="page-title"> Data table </h3>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Tables</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Data table</li>
                    </ol>
                </nav>
            </div>
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Data table</h4>
                    <div class="row">
                      
                        <div class="col-12">

                            <a href="/Roles/CreateRole" class="btn btn-success btn-fw">New</a>


                            <table id="order-listing" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>Role Name </th>
                                        <th>Action </th>
                                        
                                       
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var cat in Model)
                                    {
                                        <tr style="margin:0px;padding:0px;">
                                           
                                            <td class="col-md-8"> @cat.Name</td>
                                           

                                            <td class="col-md-4" style="margin:0px;padding:0px;">
                                                <a style="height:max-content"
                                                   asp-controller="Roles" asp-action="CreateRole" asp-route-id="@cat.Id"
                                                   class="btn btn-info btn-fw">Edit</a>

                                                <a asp-controller="Roles" asp-action="DeleteRole" asp-route-id="@cat.Id"
                                                   class="btn btn-danger btn-fw"
                                                   onclick="return confirm(" Are you sure");">Delete</a>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
    </div>
    <!-- main-panel ends -->
</div>

@section Scripts
{
  
    <!-- Plugin js for this page -->
    <script src="~/Admin/vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="~/Admin/vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <!-- End plugin js for this page -->
    <!-- Custom js for this page -->
    <script src="~/Admin/js/data-table.js"></script>
    <!-- End custom js for this page -->

  
}